apiVersion: agones.dev/v1
kind: GameServer
metadata:
  generateName: unity-simple-server-
spec:
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 7777
  template:
    spec:
      containers:
        - name: unity-simple-server
          image: planet-hunter/simple-server/unity-simple-server:0.3
          imagePullPolicy: Never
      resources:
        requests:
          memory: 128Mi
          cpu: 128m
        limits:
          memory: 256Mi
          cpu: 128m

