name: Build Push Server GHCR
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lowercase Repo Name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY,,} >> $GITHUB_ENV"
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./PlanetHunter
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/planet-hunter-server:latest
            ghcr.io/${{ env.REPO_NAME }}/planet-hunter-server:${{ github.sha }}

